name: Restrict Merges to Main

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from the 'qa' branch
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" != "qa" ]]; then
            echo "Pull requests to 'main' are only allowed from the 'qa' branch."
            exit 1
          fi