name: Sync QA with Main

on:
  workflow_dispatch:

jobs:
  sync_qa_with_main:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Git
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Compare main and qa branches
      - name: Check if `main` is ahead of `qa`
        id: check_diff
        run: |
          # Fetch all branches
          git fetch origin

          # Compare commits between `main` and `qa`
          COMMITS_AHEAD=$(git rev-list --left-only --count origin/main...origin/qa)

          # Output commits ahead as an environment variable
          echo "Main is $COMMITS_AHEAD commits ahead of QA"
          echo "commits_ahead=$(echo "$COMMITS_AHEAD" | xargs)" >> $GITHUB_ENV

      # Debugging step for commits_ahead
      - name: Debugging Commits Ahead
        run: |
          echo "Commits Ahead of QA: ${{ env.commits_ahead }}"

      # Step 4.1: Create new branch for the sync (force changes for PR creation)
      - name: Create new sync branch
        if: ${{ env.commits_ahead != '0' }}
        run: |
          # Create a new branch from main
          git checkout -b temp-sync-main-to-qa origin/main

          # Add a dummy commit to force PR creation (preserves history)
          GIT_HISTORY="Sync updated on $(date)"
          echo "$GIT_HISTORY" > .sync-history.txt
          git add .sync-history.txt
          git commit -m "[Automated] Force-PR Sync - $GIT_HISTORY"

          # Push branch to origin
          git push --force origin temp-sync-main-to-qa

      # Step 4.2: Create PR from main to qa
      - name: Create Pull Request
        id: create_pr_step
        if: ${{ env.commits_ahead != '0' }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: temp-sync-main-to-qa
          base: qa
          title: "Sync main to qa"
          body: |
            ### Pull Request Description
            This PR is automatically created to merge updates from `main` into `qa`.

            **Commits ahead in main**: ${{ env.commits_ahead }}
          labels: automated
          delete-branch: true
          commit-message: "Sync main to qa"

      # Debugging PR outputs
      - name: Debug PR Outputs
        if: ${{ steps.create_pr_step.outputs.pull-request-url != '' }}
        run: |
          echo "Pull Request URL: ${{ steps.create_pr_step.outputs.pull-request-url }}"
          echo "Pull Request Branch: ${{ steps.create_pr_step.outputs.pull-request-branch }}"

      # Step 5: Auto-approve pull request
      - name: Auto-approve pull request
        if: ${{ steps.create_pr_step.outputs.pull-request-url != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL="${{ steps.create_pr_step.outputs.pull-request-url }}"
          PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
          echo "Approving PR #$PR_NUMBER"
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews \
            -d '{"body": "Automatically approved.", "event": "APPROVE"}'

      # Step 6: Auto-merge pull request
      - name: Auto-merge pull request
        if: ${{ steps.create_pr_step.outputs.pull-request-url != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL="${{ steps.create_pr_step.outputs.pull-request-url }}"
          PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
          echo "Merging PR #$PR_NUMBER"
          curl -X PUT \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge \
            -d '{"merge_method": "squash"}'