name: Sync Main to QA

on:
  workflow_dispatch: # Allows manual triggering of this workflow

permissions:
  contents: write      # Needed to push/merge pull requests
  pull-requests: write # Needed to create and merge PRs

jobs:
  create-and-merge-pr:
    name: Create and Merge PR from Main to QA
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Fetch all branches
      - name: Fetch remote branches
        run: git fetch --all

      # Step 3: Create a new sync branch
      - name: Create sync branch
        run: |
          git checkout main
          git checkout -b sync-main-to-qa
          git push origin sync-main-to-qa

      # Step 4: Create the pull request
      - name: Create a pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-main-to-qa
          base: qa
          title: Merge main into qa
          body: |
            This is an automated pull request to sync changes from the main branch into the qa branch.
          labels: automated # Optional: Add relevant labels

      # Step 5: Approve the pull request using GitHub REST API
      - name: Approve the pull request
        if: steps.create_pr.outputs.pull-request-url != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(echo "${{ steps.create_pr.outputs.pull-request-url }}" | grep -oE '[0-9]+$')
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
               -X POST "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews" \
               -d '{"event":"APPROVE"}'

      # Step 6: Merge the pull request using GitHub REST API
      - name: Merge pull request
        if: steps.create_pr.outputs.pull-request-url != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(echo "${{ steps.create_pr.outputs.pull-request-url }}" | grep -oE '[0-9]+$')
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
               -X PUT "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge"