name: Sync QA with Main

on:
  push:
    branches:
      - main # Trigger the action when there's a push to the main branch
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full git history is fetched

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Create a new branch for the sync process
      - name: Create a new sync branch
        run: |
          git checkout -b sync-main-to-qa

      # Step 4: Merge updates from main into the new branch
      - name: Merge main into sync branch
        run: |
          git merge origin/qa --no-ff --no-commit || true
          git commit -m 'Sync: Merge main into qa' || true

      # Step 5: Push the sync branch to the repository
      - name: Push branch to remote
        run: |
          git push --set-upstream origin sync-main-to-qa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Create a pull request from the sync branch to qa branch
      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: qa
          branch: sync-main-to-qa
          title: 'Sync QA with Main'
          body: |
            This PR was automatically generated to sync the `qa` branch with the latest changes from the `main` branch.
          commit-message: 'Sync QA with Main'

      # Step 7: Automerge the pull request if created
      - name: Auto-merge pull request
        if: steps.create_pr.outputs.pull-request-url != ''
        uses: peter-evans/merge-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: ${{ steps.create_pr.outputs.pull-request-number }}
          merge-method: merge