name: Create PR from main to qa

# Trigger manually via workflow_dispatch
on:
  workflow_dispatch: # Manual trigger ONLY

permissions:
  contents: write      # Needed to push/create pull requests
  pull-requests: write # Needed to create PRs

jobs:
  create-pr:
    name: Create Pull Request from main to qa
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Create the pull request
      - name: Create PR directly from main to qa
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: qa          # Target branch
          branch: main       # Source branch
          title: Merge main into qa
          body: |
            This pull request directly merges the main branch into the qa branch.
          labels: automated # Optional: Add an "automated" label
          reviewers: ${{ github.actor }} # Optional: Add the workflow runner as the reviewer

      # Step 3: Log the PR output
      - name: Log PR creation output
        run:
          echo "Created PR: ${{ steps.create_pr.outputs.pull-request-url }}"

      # Step 4: Automatically approve the pull request
      - name: Approve the pull request
        if: steps.create_pr.outputs.pull-request-url != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(echo "${{ steps.create_pr.outputs.pull-request-url }}" | grep -oE '[0-9]+$')
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
               -X POST "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews" \
               -d '{"event":"APPROVE"}'

      # Step 5: Automatically merge the pull request
      - name: Merge the pull request
        if: steps.create_pr.outputs.pull-request-url != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(echo "${{ steps.create_pr.outputs.pull-request-url }}" | grep -oE '[0-9]+$')
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
               -X PUT "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge"