name: Create PR from main to qa

on:
  workflow_dispatch: # Manually triggered

permissions:
  contents: write      # Allows creation of branches and PRs
  pull-requests: write # Allows handling pull requests
  actions: write       # Allows approvals from the `GITHUB_TOKEN`

jobs:
  create-pr:
    name: Create and Merge Pull Request
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Create the pull request
      - name: Create PR from main to qa
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: temp-sync-main-to-qa # A temporary branch used for this workflow
          base: qa                     # Target branch (qa)
          title: Sync main with qa
          body: |
            This PR was automatically created to sync the `main` branch with the `qa` branch.
          labels: automated
          delete-branch: true          # Delete the temporary branch after successful PR merge
          reviewers: ${{ github.actor }} # Optional reviewer, usually the workflow initiator

      # Step 3: Automatically approve the pull request
      - name: Approve pull request
        if: steps.create_pr.outputs.pull-request-url != '' # Check if PR was successfully created
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(echo "${{ steps.create_pr.outputs.pull-request-url }}" | grep -oE '[0-9]+$')
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews \
            -d '{"body": "Automatically approved", "event": "APPROVE"}'

      # Step 4: Automatically merge the pull request
      - name: Merge pull request
        if: steps.create_pr.outputs.pull-request-url != '' # Check if PR was successfully created
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(echo "${{ steps.create_pr.outputs.pull-request-url }}" | grep -oE '[0-9]+$')
          curl -X PUT -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge \
            -d '{"merge_method": "squash"}'