name: Sync QA with Main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge main into qa
        run: |
          git checkout qa
          git merge origin/main

      - name: Push changes to qa
        run: git push origin qa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}